#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use DI\ContainerBuilder;
use GustavoGama\ZeebeTutorialPhp\{
    CreateOrder,
    OrderPayment,
    OrderPaymentReceived,
    OrderShipment,
    ProcessDeploy
};
use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;
use ZeebeClient\GatewayClient;

if (is_readable(__DIR__ . '/.env')) {
    (new Dotenv())->usePutenv()->loadEnv(__DIR__ . '/.env');
}

$builder = new ContainerBuilder();
$builder->addDefinitions(__DIR__ . '/config/client.php');
$container = $builder->build();

$application = new Application(
    'PHP Implementation of Cammunda official Zeebe tutorial',
    '1.0'
);

$application->add(new ProcessDeploy($container->get(GatewayClient::class)));
$application->add(new CreateOrder($container->get(GatewayClient::class)));
$application->add(new OrderPayment($container->get(GatewayClient::class)));
$application->add(new OrderShipment($container->get(GatewayClient::class)));
$application->add(new OrderPaymentReceived($container->get(GatewayClient::class)));

$application->run();
